name: Build and Run Docker Containers

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t my-flask-app -f Dockerfile.flask .

    - name: Run Docker container
      run: docker run -d -p 5000:5000 --name my-flask-app my-flask-app

    - name: Wait for the Flask app to be up
      run: |
        echo "Waiting for the Flask app to be up..."
        for i in {1..20}; do
          if curl -s http://localhost:5000/; then
            echo "Flask app is up!"
            exit 0
          fi
          sleep 10
        done
        echo "Flask app did not start in time" >&2
        exit 1

    - name: Test Flask app
      run: |
        curl -X POST http://localhost:5000/predict \
        -H "Content-Type: application/json" \
        -d '{
           "features": {
             "year": 2020,
             "gender": "Female",
             "age": 32,
             "location": "Alabama",
             "race:AfricanAmerican": 0,
             "race:Asian": 0,
             "race:Caucasian": 0,
             "race:Hispanic": 0,
             "race:Other": 1,
             "hypertension": 0,
             "heart_disease": 0,
             "smoking_history": "never",
             "bmi": 27.32,
             "hbA1c_level": 5,
             "blood_glucose_level": 100
           }
         }'
